on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: ziodave/wordpress-tests@php5.3-phpunit4.8-wordpress4.4-v0.0.1
      with:
        args: -c phpunit.xml
